"""Interfaces for different algorithms."""

from typing import Any, List, Protocol

from rssa_recommender.common.schemas import MovieLensRating


class RecommenderServiceProtocol(Protocol):
    """Centralized generic protocol to standardize calls signature."""

    def predict_top_n(self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs) -> Any: ...
    def predict_diverse_n(self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs) -> Any: ...
    def predict_diverse_community_score(
        self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs
    ) -> Any: ...
    def predict_reference_community_score(
        self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs
    ) -> Any: ...
    def predict_discounted_top_n(self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs) -> Any: ...
    def predict_controversial_items(
        self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs
    ) -> Any: ...
    def predict_hate_items(self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs) -> Any: ...
    def predict_hip_items(self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs) -> Any: ...
    def predict_no_clue_items(self, user_id: str, ratings: List[MovieLensRating], limit: int, **kwargs) -> Any: ...
